[server]
mode = "development"
port = 8888
debug = true
docs = "path/"
maps = "map_data.json"
http_timeout = 10000
jwt_timeout = 8640000
max_trx_history = 30
max_upload_size = 512000
time_zone = "Asia/Jakarta"

[development]
base_url = ""
db_driver = ""
db_host = ""
db_port = ""
db_name = ""
db_username = ""
db_password = ""
api_key = ""
redis_host = ""
redis_port = ""
redis_username = ""
redis_password = ""
secret_key = ""
newrelic_key = ""

[staging]
base_url = ""
db_driver = ""
db_host = ""
db_port = ""
db_name = ""
db_username = ""
db_password = ""
api_key = ""
redis_host = ""
redis_port = ""
redis_username = ""
redis_password = ""
secret_key = ""
newrelic_key = ""

[production]
base_url = ""
db_driver = ""
db_host = ""
db_port = ""
db_name = ""
db_username = ""
db_password = ""
api_key = ""
redis_host = ""
redis_port = ""
redis_username = ""
redis_password = ""
secret_key = ""
newrelic_key = ""