[server]
mode = "development"
port = 8888
debug = true
docs = "documents/"
maps = "map_data.json"
http_timeout = 10000
jwt_timeout = 8640000
max_trx_history = 30
max_upload_size = 512000
time_zone = "Asia/Jakarta"

[development]
base_url = "https://api.auth.com/"
db_driver = "postgres"
db_host = "localhost"
db_port = 5432
db_name = "auth_core"
db_username = "auth_core"
db_password = "auth_core_13"
api_key = "F15D3212DEFF3E1BCAB9E2CC9449E8A629F4BA908E3EA6D1E279946F8116491F"
redis_host = "localhost"
redis_port = "6379"
redis_username = ""
redis_password = ""
secret_key = "l948C3C2E935B7F448B94E6ACAFE88160EC83A1F3F9A38501A300285298091D08"
newrelic_key = "fd86539292a5f4126a420836cf1aa9dae93d76c1"

[staging]
base_url = "https://api.auth.com/"
db_driver = "postgres"
db_host = "localhost"
db_port = 5432
db_name = "auth_core"
db_username = "auth_core"
db_password = "auth_core_13"
api_key = "F15D3212DEFF3E1BCAB9E2CC9449E8A629F4BA908E3EA6D1E279946F8116491F"
redis_host = "localhost"
redis_port = "6379"
redis_username = ""
redis_password = ""
secret_key = "l948C3C2E935B7F448B94E6ACAFE88160EC83A1F3F9A38501A300285298091D08"
newrelic_key = "fd86539292a5f4126a420836cf1aa9dae93d76c1"

[production]
base_url = "https://api.auth.com/"
db_driver = "postgres"
db_host = "localhost"
db_port = 5432
db_name = "auth_core"
db_username = "auth_core"
db_password = "auth_core_13"
api_key = "F15D3212DEFF3E1BCAB9E2CC9449E8A629F4BA908E3EA6D1E279946F8116491F"
redis_host = "localhost"
redis_port = "6379"
redis_username = ""
redis_password = ""
secret_key = "l948C3C2E935B7F448B94E6ACAFE88160EC83A1F3F9A38501A300285298091D08"
newrelic_key = "fd86539292a5f4126a420836cf1aa9dae93d76c1"